#!/bin/bash

# NOTE: You should be in the 'ex' directory when executing this.

p=$(readlink $0) || p=$0
d=$(dirname  $p)
b=$(basename $p)

jruby=$d/../jruby-complete.jar

if [[ ! -f "$jruby" ]]
then
  echo "Cannot find '$jruby'."
  exit 1
fi

export DDTSAPP=.

java -jar $jruby --1.9 -I. $d/tests.rb
