Layout/EmptyLinesAroundBeginBody:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/SpaceAfterNot:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Security/Eval:
  Enabled: false
Security/YAMLLoad:
  Enabled: false

Style/AndOr:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MethodMissing:
  Enabled: false
Style/Not:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/EachWithObject:
  Enabled: false
