#!/bin/bash

p=$0
d=$(dirname  $p)
b=$(basename $p)

jruby=$d/jruby-complete.jar

if [[ ! -f "$jruby" ]]
then
  echo "Cannot find '$jruby'."
  exit 1
fi

export DDTSHOME=$d

ulimit -St unlimited -Su unlimited && java -jar $jruby --1.9 -I. $d/ts.rb $b "$@"
